### ISSUE TITLE
Chat: Share contact text too small

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#1042]
1)
![IMG_2520](https://github.com/TERITORI/teritori-dapp/assets/322761/7e1093ac-d0b8-4a05-a6ba-0cd5903c0ca4)
2)
Share contact is hard to find for new users. Maybe we should add it on the chat landing screen.
What do you think @zxxma ?

**Comment by sujal-into** [comment]
I think we don't need this one here. Because we have this here:

Uploading Simulator Screen Recording - iPhone 15 - 2024-03-11 at 16.20.08.mp4…
