### ISSUE TITLE
Wallet: misleading UI in Token Screen

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#1050]
![IMG_2527 2](https://github.com/TERITORI/teritori-dapp/assets/322761/6f63aab5-51a9-4fb7-9946-3ef40af8433f)

**Comment by omniwired** [comment]
@konole any idea?

**Comment by Konolee** [comment]
@omniwired I think it should open a new screen with 3 buttons, like: Send / Deposit / Swap + a list of recent transactions with filters. Wdyt?

**Comment by omniwired** [comment]
It's too complicated, let's just remove it.
Or just, do what Keplr does, show send.

**Comment by Konolee** [comment]
Yes, sounds great.
It should open this screen:
https://www.figma.com/file/WLEMAQXohIwBEPL5lsRrvK/Teritori---dApp?type=design&node-id=21277-5523&mode=design&t=2NcAiS7A0jQM9KWJ-11
