### ISSUE TITLE
Mobile: Feed Music UI, Button doesn’t work

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#1052]
![IMG_2529](https://github.com/TERITORI/teritori-dapp/assets/322761/048586e0-100f-450f-a3da-4d60b5edab35)

**Comment by sachin-into** [comment]
What is it suppose to do?
It didn't have any actions on web as well.

**Comment by omniwired** [comment]
@konolee @zxxma any idea?
