### ISSUE TITLE
Chat: setting screen

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#1057]
- Buttons not working 
- "Force turn on on Chats" 
  - Confirm on text: is this text required @zxxma 

Is this even possible when using BLE and other WESH features. cc @sakul-budhathoki 

![IMG_2532](https://github.com/TERITORI/teritori-dapp/assets/322761/e3e6a9f3-2921-4529-bc1f-6b3b55149f15)

**Comment by sakul-budhathoki** [comment]
@omniwired 
Force turn on Chats tab = "Weshnet will run throughout the app session; once the app closes it closes"
It is only starting Weshnet on the app starts.
By default, wesh will not start.
