### ISSUE TITLE
Mobile: Profile Page

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#1085]
Items:
- [x] Remove: Coming soon X 2
- [x] Fix layout issues
- [x] Share button relies on `window` which doesn't exist on mobile.

We could just delete this button as we have the address down there that is doing the same thing.

![image](https://github.com/TERITORI/teritori-dapp/assets/322761/b7355830-f781-4dc3-a56d-baad3a99952b)

**Comment by sachin-into** [comment]
I'm on it.
