### ISSUE TITLE
share post link uses raw id instead of network object id

### ISSUE THREAD

**Issue by n0izn0iz** [TERITORI/teritori-dapp#1120]
the url format in share post buttons is not good:

current: `https://app.teritori.com/feed/post/2e16610f-a138-402c-ae9a-c7fa63a89edd`
expected: `https://app.teritori.com/feed/post/tori-2e16610f-a138-402c-ae9a-c7fa63a89edd`
the expected id is generated via `getNetworkObjectId(network.id, post.identifier)`

unless this is fixed, the link does not work if the wrong network is selected

**Comment by ChiragPansuriya-iView** [comment]
working on it

**Comment by WaDadidou** [comment]
It's fixed, so I close this issue
![image](https://github.com/user-attachments/assets/32f07e4e-178b-4ae9-be29-9f91d579f462)
