### ISSUE TITLE
Status bar in android (all screens of seed phrase) is cropped

### ISSUE THREAD

**Issue by sujal-into** [TERITORI/teritori-dapp#1126]
![48c6ce7e-37d2-44f3-918b-a9f607c5032f](https://github.com/TERITORI/teritori-dapp/assets/155436948/051a6c11-e345-410c-a3eb-535316e5d0f9)

**Comment by sujal-into** [comment]
working on this

**Comment by sakul-budhathoki** [comment]
#1131
