### ISSUE TITLE
Wallet: disable multiple wallets for first version

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#1148]

**Comment by clegirar** [comment]
Checked the PR of Omniwired (https://github.com/TERITORI/teritori-dapp/pull/1149) and it's related to a mobile version, or at least a non-web version https://github.com/TERITORI/teritori-dapp/blob/main/packages/store/slices/settings.ts#L53

So i think he talked about disable multiple wallets for the first mobile version, so it's probably not relevant anymore 👍

**Comment by WaDadidou** [comment]
==> As the mobile version is not in our focuses now, we can close yes I guess.
To facilitate the resumption of this work, here are the important changes:

https://github.com/TERITORI/teritori-dapp/pull/1149/files#diff-9c8833f758259db19048c07b0a50b43fd051bd6ab6aa50b3af7476efed4c48adR49

https://github.com/TERITORI/teritori-dapp/pull/1149/files#diff-9c8833f758259db19048c07b0a50b43fd051bd6ab6aa50b3af7476efed4c48adR76

https://github.com/TERITORI/teritori-dapp/pull/1149/files#diff-bb0c2a6ec33fe9331ecb1b65772d593ed8db612f2cabe6f2f2f8fe1466ec6a7cR91
