### ISSUE TITLE
Market Place : Ui break in mobile view

### ISSUE THREAD

**Issue by ChiragPansuriya-iView** [TERITORI/teritori-dapp#1168]
Market Place Ui break in mobile view 
 The text is overlapped and in search input search icon is not shown properly
![simulator_screenshot_FE1ADCAC-C112-4E9A-9772-34D172C7F7B9](https://github.com/TERITORI/teritori-dapp/assets/134677881/084b3cd4-0f27-4aa3-9817-73d1b05c63f6)

**Comment by ChiragPansuriya-iView** [comment]
working on this

**Comment by n0izn0iz** [comment]
done by @WaDadidou
