### ISSUE TITLE
a front issue when creating a new article

### ISSUE THREAD

**Issue by MalekLahbib** [TERITORI/teritori-dapp#1272]
Hello,
when I was testing your social feed app, I noticed when I was trying to create a new article, that in the "Article content" container when I click on "Type message here" I can't write anything, I have to click beside to have focus. After inspecting the page, I think that the div containing "Type message here" is the problem.
![Screenshot from 2024-09-12 17-56-09](https://github.com/user-attachments/assets/13652a3f-fa14-4ca4-aebc-93756f493806)

**Comment by n0izn0iz** [comment]
@WaDadidou can you check pls

**Comment by WaDadidou** [comment]
=> Related to https://github.com/TERITORI/teritori-dapp/issues/1353

@MalekLahbib 
We use `draft-js-plugins/editor` to write/read Articles, and provide a `placeholder` to the `Editor` component, that is weirdly handled: https://github.com/TERITORI/teritori-dapp/blob/main/packages/components/socialFeed/RichText/RichText.web.tsx#L432

We planned to replace draft-js by a markdown support, and refacto the Articles creation.
This is a known issue and hope we could put ressources on this refacto as soon as possible.

Thank you for your report, and sorry for the delay.

**Comment by WaDadidou** [comment]
I made a PR: https://github.com/TERITORI/teritori-dapp/pull/1372
