### ISSUE TITLE
New article error

### ISSUE THREAD

**Issue by MalekLahbib** [TERITORI/teritori-dapp#1273]
I'm trying to create a new article but I'm having an error message.
![Screenshot from 2024-09-12 18-02-57](https://github.com/user-attachments/assets/20b0e3f7-568a-4d75-9731-cddf7306a488)

**Comment by n0izn0iz** [comment]
same, portal loop is not supported currently, we should show something to the user about that though

**Comment by MalekLahbib** [comment]
thanks @n0izn0iz
