### ISSUE TITLE
No feeds displays when refreshing the page, when adena wallet is connected

### ISSUE THREAD

**Issue by MalekLahbib** [TERITORI/teritori-dapp#1274]
When I refresh the page after connecting the wallet, there's no feeds that are displayed, and I have error messages on the console. Is this the way it's supposed to work?
![Screenshot from 2024-09-12 18-12-50](https://github.com/user-attachments/assets/876b0c37-530e-44c2-8174-f23f3dac4174)

**Comment by n0izn0iz** [comment]
the social feed realm "undeployed" from portal loop in a recent update, we're not supporting portal loop at all times currently

**Comment by MalekLahbib** [comment]
thanks @n0izn0iz for your response, switched to test 4 on my adena wallet and it's working.
