### ISSUE TITLE
[bug] : Close button 

### ISSUE THREAD

**Issue by DIGIX666** [TERITORI/teritori-dapp#1290]
Hey 👋🏼
I wanted to see to send gnot to a post and I pressed the cross because I had the wrong post. I found this error
`Error: Invalid string format. Only non-negative integers in decimal representation supported`

https://github.com/user-attachments/assets/12efc875-ce7e-4b09-9a81-2a7060e3a239

**Comment by zxxma** [comment]
thanks for report

**Comment by WaDadidou** [comment]
I opened a PR fixing the issue, thanks
