### ISSUE TITLE
bug(dao-teritori): cannot execute a DAO proposal to post on social feed

### ISSUE THREAD

**Issue by MikaelVallenet** [TERITORI/teritori-dapp#1337]
First have to merge this PR to be able to create a proposal
depends on #1336

![image](https://github.com/user-attachments/assets/de46ec27-829c-4cd3-8159-1770087f6995)

**Comment by n0izn0iz** [comment]
do you have funds on the DAO?

**Comment by MikaelVallenet** [comment]
> do you have funds on the DAO?

I did not do anything to have funds on the DAO, so no i guess.
How can i see that ? i will try to send money to the DAO to see the behavior

**Comment by n0izn0iz** [comment]
done
