### ISSUE TITLE
bug(feed): can't reply because uses global post id instead of network-local identifier

### ISSUE THREAD

**Issue by n0izn0iz** [TERITORI/teritori-dapp#1347]

**Comment by WaDadidou** [comment]
The `parent_post_identifier` used is the post's global id instead of local id at the post's creation

![image](https://github.com/user-attachments/assets/aa3acae8-b7b6-4d2e-8ab3-ec1e3336bd12)

**Comment by n0izn0iz** [comment]
#1375
