### ISSUE TITLE
chore(feed): Remove this useless useEffect used for Video render

### ISSUE THREAD

**Issue by WaDadidou** [TERITORI/teritori-dapp#1350]
It's here: https://github.com/TERITORI/teritori-dapp/blob/main/packages/screens/FeedPostView/components/FeedPostDefaultView.tsx#L57-L62

Why removing that ?

`FeedPostDefaultView` is only called in `FeedPostView`, but this `useEffect` redirects to `FeedPostView`.
Also, the `PostCategory.Video` case is already handled in `FeedPostView`: https://github.com/TERITORI/teritori-dapp/blob/main/packages/screens/FeedPostView/FeedPostView.tsx#L81-L82.
So, there is no reason to redirect to `FeedPostView` for the `PostCategory.Video` case

**Comment by System625** [comment]
Hello, I would to love to work on this
I am able to remove the useeffect while still maintaining readability and efficiency

**Comment by jahrulezfrancis** [comment]
Is this issue still available? I'd love to work on it

**Comment by addegbenga** [comment]
I will love to work on this:
ETA 24hrs

**Comment by Ayotomiwadavid** [comment]
I'd be happy to do this.
