### ISSUE TITLE
bug(feed): AudioNote thumbnail is not shown in MediaPlayerBar

### ISSUE THREAD

**Issue by WaDadidou** [TERITORI/teritori-dapp#1365]
![image](https://github.com/user-attachments/assets/443c7207-e656-4780-8c8b-b6661b05d00a)

But it's ok with MusicAudio

![image](https://github.com/user-attachments/assets/786b6516-9612-4411-ad09-f3238c357bf4)
![image](https://github.com/user-attachments/assets/6149a042-213e-4ef5-9263-886a34a15ea7)

**Comment by n0izn0iz** [comment]
do we really want audionotes to have thumbnails?

**Comment by n0izn0iz** [comment]
an audio note is like a vocal message in a messaging app, I don't think it should have a thumbnail

**Comment by WaDadidou** [comment]
> do we really want audionotes to have thumbnails?
Currently, it can.
But we could remove it yes
@zxxma , wdyt ?

![image](https://github.com/user-attachments/assets/5b99470b-7d0a-4edf-91c2-d56aa8068b52)

**Comment by n0izn0iz** [comment]
> BUT, we'll always have the default thumbnail in the media player

it should show the user avatar in this case IMO

**Comment by WaDadidou** [comment]
> > BUT, we'll always have the default thumbnail in the media player
> 
> it should show the user avatar in this case IMO

Ah yes yes.
Btw it should be the default thumbnail in the media player

**Comment by n0izn0iz** [comment]
closing as won't do, opened https://github.com/TERITORI/teritori-dapp/issues/1407
