### ISSUE TITLE
bug(feed): dezoomed map by default instead of Paris

### ISSUE THREAD

**Issue by WaDadidou** [TERITORI/teritori-dapp#1367]
### We want

![image](https://github.com/user-attachments/assets/2e33b4f5-99f5-4fd6-88d9-d1424c13f587)

### We have

![image](https://github.com/user-attachments/assets/20ce9e0d-e884-4e0e-81a3-df6c4bcf6cf3)

**Comment by n0izn0iz** [comment]
https://github.com/TERITORI/teritori-dapp/pull/1399
