### ISSUE TITLE
bug(feed): reactions only show up on post details page

### ISSUE THREAD

**Issue by n0izn0iz** [TERITORI/teritori-dapp#1374]
Feed page:
<img width="1155" alt="Screenshot 2024-11-16 at 22 57 57" src="https://github.com/user-attachments/assets/815e8a12-b210-47c7-a999-b22e6a4c95d6">

Post page (https://app.teritori.com/feed/post/tori-707b16ab-3395-46f5-918b-0456af5d65ec):
<img width="1175" alt="Screenshot 2024-11-16 at 22 58 15" src="https://github.com/user-attachments/assets/265a3c41-6b42-424e-8ada-7aa2b603b740">

**Comment by n0izn0iz** [comment]
seems indexing is working
<img width="1512" alt="Screenshot 2024-11-16 at 22 58 42" src="https://github.com/user-attachments/assets/55c22b55-f55a-4235-86fe-b58cc8ced6a3">

**Comment by n0izn0iz** [comment]
tx seem ok (no global post id like in #1347)

```
{
  "react_post": {
    "icon": "😇",
    "identifier": "707b16ab-3395-46f5-918b-0456af5d65ec",
    "up": true
  }
}
```

**Comment by WaDadidou** [comment]
Precision: It works with Gno
