### ISSUE TITLE
refacto(feed): Factorize posts Zod types parsing

### ISSUE THREAD

**Issue by WaDadidou** [TERITORI/teritori-dapp#1403]
We use `zodTryParseJSON` to validate the fetched posts metadata.
We have many shapes for posts (track, article, etc..)
Due to these different shapes, we need to "anticipate" it and `zodTryParseJSON` the "possible" shapes.

Examples:
- https://github.com/TERITORI/teritori-dapp/blob/bugfix/video-audio-map/packages/screens/FeedPostView/components/FeedPostArticleView.tsx#L108
- https://github.com/TERITORI/teritori-dapp/blob/bugfix/video-audio-map/packages/screens/FeedPostView/components/FeedPostArticleView.tsx#L108
- https://github.com/TERITORI/teritori-dapp/blob/bugfix/video-audio-map/packages/screens/Mini/Feed/components/detailView/MiniArticlePostDetails.tsx#L59

In the map, we handle all these shapes, because we display videos, tracks, articles, etc..
So, example with all these shapes:

````
const videoPostMetadata = zodTryParseJSON(
  ZodSocialFeedVideoMetadata,
  post.metadata,
);
const trackMetadata = zodTryParseJSON(
  ZodSocialFeedTrackMetadata,
  post.metadata,
);
const articleMetadata = zodTryParseJSON(
  ZodSocialFeedArticleMetadata,
  post.metadata,
);
const postMetadata = zodTryParseJSON(
  ZodSocialFeedPostMetadata,
  post.metadata,
);
const metadataToUse = videoPostMetadata || trackMetadata || articleMetadata || postMetadata;
````

==> Should we add a function that `zodTryParseJSON` all these shapes and returns `metadataToUse` ?
Or make a refacto on these shapes ?

**Comment by n0izn0iz** [comment]
use `zodSocialFeedCommonMetadata`
