### ISSUE TITLE
bug: No Cosmos Hub in Deposit modal

### ISSUE THREAD

**Issue by WaDadidou** [TERITORI/teritori-dapp#1435]
### "From unknown"

Related to https://github.com/TERITORI/teritori-dapp/issues/1345 ?

In this exemple, the Cosmos Hub network is not found from here: https://github.com/TERITORI/teritori-dapp/blob/main/packages/components/TopMenu/TopMenuMyWallets.tsx#L263

![image](https://github.com/user-attachments/assets/b02afd54-fe8e-4c70-adf0-e4a40ca5e0b3)

**Comment by n0izn0iz** [comment]
we don't have a cosmos hub channel on testnet
