### ISSUE TITLE
Inconsistent Stake navigation

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#367]
On the home page:

![image](https://user-images.githubusercontent.com/322761/205635154-888b9c40-693b-4adb-b95d-2929c5453acd.png)

Pointing at: https://explorer.teritori.com/teritori/staking 
![image](https://user-images.githubusercontent.com/322761/205635498-50aec1ba-ddb3-42c4-9ddd-a4e0430741ac.png)

Inside the dApp:

![image](https://user-images.githubusercontent.com/322761/205635330-eec9e223-a698-416c-964c-113aff2c02bd.png)

This is confusing for new users.

These 2 actions should go to the same place, or else explain what is the difference between them.

**Comment by n0izn0iz** [comment]
landing page has changed
