### ISSUE TITLE
[The R!OT] Top menu: Rarity

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#381]
I feel we should add a UI element to let users know this will open  in a new tab.

![image](https://user-images.githubusercontent.com/322761/207542279-119d5142-17ed-4d0c-9855-0819a61cf776.png)

Maybe one of these: https://icons8.com/icons/set/new-tab ??

![image](https://user-images.githubusercontent.com/322761/207542440-e3787b50-42a3-4df9-b9d8-e323097211d2.png)

**Comment by n0izn0iz** [comment]
rarity link is broken now
