### ISSUE TITLE
[RFC] Performance Improvements and optimizations

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#404]
Let's use this issue to track what needs to be done, as well as ideas on how to optimize the app.

# Media assets optimizations
  - [x] Optimize committed files. 
    - [x]  `nft.svg` its a base64 image, and expo complains it can't be optimized | `assets/icons/nft.svg as it exceeds the max of 500KB.`

  - [x] Set up an optimization proxy | tracked at #180 

# Optimize queries & indexer
- [ ] Idea 1
- [ ] Idea 2
- [ ] Pagination?

 ### Idea 1 Stop pinging the RPC when the user is not looking at the page.

 ```
document.addEventListener("visibilitychange", () => {
  if (document.hidden) {
    // stop
  } else {
    // resume
  }
});
```

**Comment by n0izn0iz** [comment]
done
