### ISSUE TITLE
TNS: Inconsistent mint

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#517]
I'm allowed to "try" to register and existing TNS.

How to reproduce:
- Find an existing TNS, for example: `tns.tori`
- Try to register TNS (capital letters)
- You won't be able to do it, as tns are case insensitive and TNS and tns are the same for the smart contract.

How to fix?
Needs better checking against the backend.

Demo:

https://user-images.githubusercontent.com/322761/230858209-27a2d7da-8667-4483-a898-b1dd09012fd1.mp4

Demo 2:

https://user-images.githubusercontent.com/322761/230858451-a0dc1479-7182-463d-9c15-8f93205c09eb.mp4

**Comment by n0izn0iz** [comment]
done
