### ISSUE TITLE
Home: Optimize RPC calls

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#521]
Currently there are huge amount of traffic, even when the site is idle.

The following is a capture of the homepage (https://app.teritori.com/ ) after scrolling to the bottom and not moving.

https://user-images.githubusercontent.com/322761/230874199-b6371876-555f-4992-aaa6-3d10cd72dd18.mp4

**Comment by n0izn0iz** [comment]
done or need more precision
