### ISSUE TITLE
Social feed: videos don't have a thumbnail

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#530]
![image](https://user-images.githubusercontent.com/322761/231042045-c541f1e4-28ac-41b4-b249-ca8eb1b94a2a.png)

## It also seems that all videos get loaded at the same time, it should only load after the user click on the video thumbnail and it should "stream", I shouldn't have to wait for the whole video to be downloaded.

**Comment by WaDadidou** [comment]
After many fixes on Social Feed, I can't reproduce this issue, I close
