### ISSUE TITLE
Social feed: fix the scrollbar on emoji list

### ISSUE THREAD

**Issue by FerrymanGMI** [TERITORI/teritori-dapp#542]
Upon clicking on the emoji icon to pop-up the emoji modal, the scroolbar overflows on the emojis list. Maybe adding a little bit of padding/margin would do the trick (as seen on Twitter for instance).
![image](https://user-images.githubusercontent.com/76942962/231473628-d17075a3-cf3f-4162-864d-6ff504110d54.png)

**Comment by omniwired** [comment]
Fixed looks like this
![Kapture 2023-04-13 at 11 30 07](https://user-images.githubusercontent.com/322761/231632257-8f5cb2c7-5932-4a90-aa3e-bf53451d4e7d.gif)
