### ISSUE TITLE
Underscore in TNS Registration makes an error

### ISSUE THREAD

**Issue by WaDadidou** [TERITORI/teritori-dapp#644]
If you try to register a name including a `-`, the amount of tokens available won't load. You will see an error generated from https://github.com/TERITORI/teritori-dapp/blob/ee896a98c1079a46107f00dbae2cf71608a437ec/packages/screens/TeritoriNameService/TNSMintNameScreen.tsx#L296C43-L296C43
![image](https://github.com/TERITORI/teritori-dapp/assets/50441633/ae60bf18-541e-4c14-b3a4-d86ae88e1b5a)

===> We need to better control the entered `name`, respecting the TNS formats accepted. maybe need a kind of regexp directly fetched from the backend ?
(In `TNSNameFinderModal.tsx`, `FindAName.tsx`, `NameDataForm.tsx`, etc...)

![image](https://github.com/TERITORI/teritori-dapp/assets/50441633/96f9c2fc-5b33-43e1-ad9d-e05f6d51c57e)

**Comment by n0izn0iz** [comment]
You can get the list of available character from the contract

**Comment by n0izn0iz** [comment]
As a temporary hack you can also query the booking price and I think it returns an error if there is a wrong character

**Comment by n0izn0iz** [comment]
done
